//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pin.Spoticlone.Core.Entities
{
	using System;
	using System.Collections.Generic;


	public class Album : EntityBase
	{
		public string Name { get; set; }
		public DateTime ReleaseDate { get; set; }
		public string SpotifyId { get; set; }
		public Uri Image { get; set; }
		public Guid ArtistId { get; set; }
		public Artist Artist { get; set; }
		public ICollection<Track> Tracks { get; set; }
	}
}
