//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pin.Spoticlone.Core.Entities
{
    using System;
    
    
    public class ArtistGenre
    {
        
		public Guid ArtistId { get; set; }
		public Guid GenreId { get; set; }
		public Artist Artist { get; set; }
		public Genre Genre { get; set; }
    }
}
